import "./globals.css";
import type { Metadata } from "next";
import Nav from "@/components/Nav";
import React from "react";
import { Provider } from "@/app/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={false}>
      <body>
        <Provider>
          <Nav />
          <div className="text-center">
            <p
              className=" text-sm md:text-2xl font-bold text-white bg-black p-2
            dark:text-black dark:bg-white"
            >
              FREE SHIPPING ON ORDERS OVER $100
            </p>
          </div>
          <main className="px-4 w-full md:w-[95%] lg:w-[90%]  2xl:w-[1400px] mx-auto">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
