import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="fixed w-full h-[30px] bg-gray-500 p-2 box-content"></header>
        <main className="pt-[50px]">{children}</main>
      </body>
    </html>
  );
}
